---
title: "ggplot2 for 2 variables"
author: "Chia-Yu Wei"
date: "2023-11-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2 Variables Plotting with ggplot2
```{r}
library(ggplot2)
library(ggplot2movies)
```


```{r}
pl <- ggplot(movies, aes(x = year, y = rating))

pl2 <- pl + geom_bin2d()
pl2 + scale_fill_gradient(high = 'red', low = 'green')
```
```{r}
# Change the shize of grid (square -> rectangle)
pl2 <- pl + geom_bin2d(binwidth = c(1, 3))
pl2 + scale_fill_gradient(high = 'red', low = 'green')
```

```{r}
# change the shape of the points.
# install.package('hexbin')
pl2 <- pl + geom_hex()
pl2 + scale_fill_gradient(high = 'red', low = 'green')
```

```{r}
# Density
pl2 <- pl + geom_density2d()
pl2
```

\newpage
# Theme
```{r}
library(ggplot2)
pl <- ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point()

print(pl)
```
```{r}
# theme_minimal: minimize information
theme_set(theme_minimal())
pl
```
```{r}
# Dark theme
pl + theme_dark()
```

# Package about ggplot
```{r}
# install.package('ggthemes')
library(ggthemes)
```
```{r}
# We have more option for theme
pl + theme_economist()
pl + theme_fivethirtyeight()
```
